IF (NOT WIN32)
    include(CheckCCompilerFlag)
    CHECK_C_COMPILER_FLAG("-std=c11" COMPILER_SUPPORTS_C11)
    if( COMPILER_SUPPORTS_C11 )
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -std=c11")
    else()
        message(STATUS "The compiler ${CMAKE_C_COMPILER} has no C11 support. Please use a different C compiler.")
    endif()

    include(CheckCXXCompilerFlag)
    CHECK_CXX_COMPILER_FLAG("-std=c++11" COMPILER_SUPPORTS_CXX11)
    if( COMPILER_SUPPORTS_CXX11 )
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
    else()
        message(STATUS "The compiler ${CMAKE_CXX_COMPILER} has no C++11 support. Please use a different C++ compiler.")
    endif()

    set(CMAKE_C_FLAGS_DEBUG "$ENV{CFLAGS} -O0 -Wall -Wno-unused-variable -g -ggdb")
    set(CMAKE_C_FLAGS_RELEASE "$ENV{CFLAGS} -O3 -Wall")
    message("Build Information: " ${CMAKE_BUILD_TYPE} ${CMAKE_C_FLAGS})

    set(CMAKE_CXX_FLAGS_DEBUG "$ENV{CFLAGS} -O0 -Wall -Wno-unused-variable -g -ggdb")
    set(CMAKE_CXX_FLAGS_RELEASE "$ENV{CFLAGS} -O3 -Wall")
    message("Build Information: " ${CMAKE_BUILD_TYPE} ${CMAKE_CXX_FLAGS})
ENDIF ()
